version: '3'

services:
  app:
    build: .
    image: aquavitae_app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src/static/images:/app/src/static/images
    networks:
      network:
        ipv4_address: 172.28.0.2

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      network:
        ipv4_address: 172.28.0.3

volumes:
  postgres-data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
