"""add_amount_column_to_diary.py

Revision ID: 846bf47c7c1c
Revises: edc0a99d4fb6
Create Date: 2023-12-04 16:25:11.936439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846bf47c7c1c'
down_revision = 'edc0a99d4fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diary", sa.Column("amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diary", "amount")
    # ### end Alembic commands ###
